Controllers/CustomerExecutiveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Retail_Bank_Management.Models;

namespace Retail_Bank_Management.Controllers
{
    [Authorize(Roles = "AccountExecutive")]
    public class CustomerExecutiveController : Controller
    {
        private ICustomerRepository _customerRepository;
        private IAccountRepository _accountRepository;

        public CustomerExecutiveController(ICustomerRepository customerRepository, IAccountRepository accountRepository)
        {
            _customerRepository = customerRepository;
            _accountRepository = accountRepository;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Update(string SearchString)
        {
            Customer model = _customerRepository.GetCustomer(Convert.ToInt32(SearchString));
            return View(model);
        }

        [HttpPost]
        public IActionResult Update(Customer customerChanges)
        {
            if (ModelState.IsValid)
            {
                ViewData["success"] = "true";
                Customer newCustomer = _customerRepository.Update(customerChanges);
                return View(newCustomer);
                
            }
            ViewData["success"] = "false";
            return View(customerChanges);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Customer customer)
        {
            if(ModelState.IsValid)
            {
                Customer newCustomer = _customerRepository.Add(customer);
                return View(newCustomer);
            }
            return View();
        }

        [HttpGet]
        public IActionResult Delete(string SearchString)
        {
            Customer model = _customerRepository.GetCustomer(Convert.ToInt32(SearchString));
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(Customer customer)
        {
            ViewData["success"] = "true";
            Customer model = _customerRepository.Delete(customer.CustomerID);
            return View(model);
        }

        [HttpGet]
        public IActionResult CreateAccount()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateAccount(Account account)
        {
            Account newAccount = new Account() 
            { CustomerID = account.CustomerID, Balance = account.Balance,
              AccountType = account.AccountType, Message = "Successfully Created", Status = "Active", LastUpdated = DateTime.Now };
            string customerName = _customerRepository.GetCustomer(account.CustomerID).Name;
            ViewData["customerName"] = customerName;
            Account model = _accountRepository.Add(newAccount);
            return View(model);
        }

        [HttpGet]
        public IActionResult GetAccount(string CustomerID)
        {
            DeleteAccountViewModel deleteAccountViewModel = null;
            Customer cust = _customerRepository.GetCustomer(Convert.ToInt32(CustomerID));
            Account acc = _accountRepository.GetAccountByCustomerID(Convert.ToInt32(CustomerID));
            if(cust != null && acc != null)
            {
                string name = cust.Name;
                int accountID = acc.AccountID;
                deleteAccountViewModel = new DeleteAccountViewModel() { CustomerName = name, AccountID = accountID };
            }
            else
            {
                ViewData["DeleteSuccess"] = "false";
                deleteAccountViewModel = new DeleteAccountViewModel() { CustomerName = "No Account", AccountID = 000000000 };
            }
            return View("DeleteAccount", deleteAccountViewModel);
        }

        [HttpGet]
        public IActionResult DeleteAccount()
        {
            return View();
        }

        [HttpPost]
        public IActionResult DeleteAccount(DeleteAccountViewModel model)
        {
            Account account = _accountRepository.Delete(model.AccountID);
            if (account != null)
                ViewData["DeleteSuccess"] = "true";
            else 
                ViewData["DeleteSuccess"] = "false";
            return View(model);
            //return model.AccountID;
        }

        [HttpGet]
        public IActionResult AccountStatus()
        {
            List<Account> accounts = _accountRepository.GetAllAccounts().ToList();
            return View(accounts);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Retail_Bank_Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg shadow p-3 mb-5 bg-white rounded">
            <a class="navbar-brand" href="#">Xplore Bank</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Customer
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" asp-controller="CustomerExecutive" asp-action="Create">Create Customer</a>
                            <a class="dropdown-item" asp-controller="CustomerExecutive" asp-action="Update">Update Customer</a>
                            <a class="dropdown-item" asp-controller="CustomerExecutive" asp-action="Delete">Delete Customer</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Account
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" asp-controller="CustomerExecutive" asp-action="CreateAccount">Create Account</a>
                            <a class="dropdown-item" asp-controller="CustomerExecutive" asp-action="DeleteAccount">Delete Account</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Status
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" asp-controller="CustomerExecutive" asp-action="CustomerStatus">Customers Status</a>
                            <a class="dropdown-item" asp-controller="CustomerExecutive" asp-action="AccountStatus">Accounts Status</a>
                        </div>
                    </li>
                </ul>

            </div>
            <div class="form-inline my-2 my-lg-0">
                <form method="post" asp-action="Logout" asp-controller="Home">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Logout @User.Identity.Name</button>
                </form>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Retail_Bank_Management - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout1.cshtml
@inject SignInManager<IdentityUser> signInManager;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Retail_Bank_Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    
    <header>
        <nav class="navbar navbar-expand-lg shadow p-3 mb-5 bg-white rounded ">
            <a class="navbar-brand" href="#">Xplore Bank</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="CashierTeller" asp-action="AccountDetails">Account Details</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle border-left" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Transactions
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" asp-controller="CashierTeller" asp-action="Deposit">Deposit</a>
                            <a class="dropdown-item" asp-controller="CashierTeller" asp-action="Withdraw">Withdraw</a>
                            <a class="dropdown-item" asp-controller="CashierTeller" asp-action="Transfer">Transfer</a>
                        </div>
                    </li>
                    <li class="nav-item border-left">
                        <a class="nav-link" asp-action="AccountStatement">Account Statement</a>
                    </li>
                </ul>
            </div>
            @if (signInManager.IsSignedIn(User))
            {
                <div class="form-inline my-2 my-lg-0">
                    <form method="post" asp-action="Logout" asp-controller="Home">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Logout @User.Identity.Name</button>
                    </form>
                </div>
            }
            else
            {
                <a asp-action="Login" asp-controller="Home" class="btn btn-secondary my-2 my-sm-0" type="button">Login</a>
            }

        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Retail_Bank_Management - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Retail_Bank_Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary shadow p-3 mb-5 ">
            <a class="navbar-brand" href="#">Xplore Bank</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" asp-action="Login" asp-controller="Home">Login</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" asp-action="Register" asp-controller="Home">Register</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Retail_Bank_Management - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>